stages:
- stage: CD_PREPROD
  displayName: CD PREPROD
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - checkout: none
    
    - script: echo I am CD Stage
      displayName: Run a one-line script2