variables:
- template: pipeline-templates/variables/build.yml  # Template reference
pool:
  vmImage: ubuntu-latest
steps:
- checkout: none

- script: echo ${{ variables.arch }} ${{ variables.config }}