variables:
- template: pipeline-templates/variables/build.yml  # Template reference
- name: img
  value: ubuntu-latest
pool:
  vmImage: ${{ variables.img }}
steps:
- script: echo ${{ variables.arch }} ${{ variables.config }}