trigger:
  - master
  
pool: 
  vmImage: ubuntu-latest

jobs:
- job: PreWork
  steps:
  - checkout: none
  
  - script: "Do pre-work"

- job: PostWork
  pool: windows-latest
  steps:
  - checkout: none

  - script: "Do post-work using a different hosted image"