parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - checkout: none

  - script: echo "npm install"
  
  - script: echo "npm test"
  
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: echo "sign"