# In the following example, the bash step can only set the value of the sauce variable.
# When the pipeline runs, the secretSauce variable is not set, and a warning is displayed on the pipeline run page.

steps:
  - checkout: none

  - bash: |
      echo "##vso[task.setvariable variable=sauce;]crushed tomatoes"
      echo "##vso[task.setvariable variable=secretSauce;]crushed tomatoes with garlic"
    target:
     settableVariables:
      - sauce
    name: SetVars

  - bash: 
      echo "Sauce is $(sauce)"
      echo "secretSauce is $(secretSauce)"
    name: OutputVars