# This example runs three stages, one after another. The middle stage runs two jobs in parallel.

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - checkout: none
      - script: echo Building!
  - stage: Test
    jobs:
    - job: TestOnWindows
      steps:
      - checkout: none
      - script: echo Testing on Windows!
    - job: TestOnLinux
      steps:
      - checkout: none
      - script: echo Testing on Linux!
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - checkout: none
      - script: echo Deploying the code!